### ISSUE TITLE
Unable to install latest version (2.2.0) via Vortex

### ISSUE THREAD

**Issue by linkinkampf19** [DaymareOn/hdtSMP64#126]
EDIT: I'm a bit dopey, I did just extract one of the skse folders (no CUDA AVX2) and it was 3 files. Sorry for the derp. Still strange that the archive is seen as broken within Vortex though. 

Good afternoon, I'm having a weird issue with attempting to install the latest version of the mod (2.2.0). I'm running a heavily modded SkyrimVR with ~570 mods. I have had an earlier FSMP version installed previously with only minimal error within the game (CTD that I'm still trying to pinpoint, hinting at NiNodes). Upon downloading the latest version of FSMP, the installation fails with the below details:

```
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at FomodInstaller.Scripting.XmlScript.ConditionalOptionTypeResolver.ResolveConditionMessage(ConditionStateManager csmState, CoreDelegates coreDelegates)
   at FomodInstaller.Scripting.XmlScript.Option.GetConditionMessage(ConditionStateManager csmState, CoreDelegates coreDelegates)
   at FomodInstaller.Scripting.XmlScript.XmlScriptExecutor.<>c__DisplayClass14_2.<sendState>b__5(Option option)
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FomodInstaller.Scripting.XmlScript.XmlScriptExecutor.<>c__DisplayClass14_4.<sendState>b__7(OptionGroup group)
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FomodInstaller.Scripting.XmlScript.XmlScriptExecutor.<>c__DisplayClass14_0.<sendState>b__3(InstallerStep[] steps, Int32 idx)
   at FomodInstaller.Scripting.XmlScript.XmlScriptExecutor.sendState(IList`1 lstSteps, String strPrefixPath, Int32 stepIdx)
   at FomodInstaller.Scripting.XmlScript.XmlScriptExecutor.DoExecute(IScript scpScript, String dataPath, Object preset)
   at CallSite.Target(Closure , CallSite , Object )
   at FomodInstaller.Scripting.ScriptExecutorBase.Execute(IScript p_scpScript, String p_strDataPath, Object preset)
   at CallSite.Target(Closure , CallSite , Object )
   at FomodInstaller.ModInstaller.Installer.ScriptedModInstall(Mod modArchive, Object preset, ProgressDelegate progressDelegate, CoreDelegates coreDelegate)
   at CallSite.Target(Closure , CallSite , Object )
   at FomodInstaller.ModInstaller.Installer.Install(List`1 modArchiveFileList, List`1 stopPatterns, String pluginPath, String scriptPath, Object preset, Boolean validate, ProgressDelegate progressDelegate, CoreDelegates coreDelegate)
   at CallSite.Target(Closure , CallSite , Object )
   at ModInstallerIPC.Server.DispatchInstall(String id, JObject data)
   at ModInstallerIPC.Server.Dispatch(String id, JObject data)
   at ModInstallerIPC.Server.<>c__DisplayClass24_0.<<OnReceived>b__1>d.MoveNext()
```
1. Download FSMP from Nexus
2. Install via Vortex (direct, manual, and recompressed manual)
3. See error

**Expected behavior**
Mod gets installed just like any other.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro

** FSMP**
- 2.2.0

**SKSE**
- 2.00.12 VR

**Skyrim**
- 1.4.15

**Required files**
- Don't have them as the mod will not install.

**Additional context**
As noted above in the steps, I have tried installing multiple times via multiple measures. While I've not just tried dumping the files into the Skyrim folder (that'd be barbaric :P ), I have attempted both Vortex and Manual downloads, as well as unarchiving the mod and then rezipping it via 7zip. All instances result in the same error.

**Comment by linkinkampf19** [comment]
Sorry for the lapse, but I did make some headway. I ended up testing the issue by taking the core files from 2.2.0 and just dropping them over to the previous Vortex installed version, and I've not had any issue yet. I'll backpedal and try your archive once settled tonight. 

As for your prior query, I was able to use FSMP alongside the necessary MCM, and everything seems to be operating fine. I was one of the users who initially had trouble with the MCM even showing up, but seems like all is well now.

I'll get back to you sometime this evening to update my findings.

Thanks!
